name: Scala CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]
  repository_dispatch:


jobs:
  create_jar:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: pull_repo
      run: git clone https://github.com/Bxnce/uno.git
    - name: goto_uno
      run: |
        ls
        cd uno
        sbt package
    - name: move_back_cp_and_delete
      run: | 
        ls
        rm -f uno_web/lib/uno*.jar ||true
    - name: testse
      run: |
        ls
        mkdir -p lib 
        cp uno/target/scala-*/*.jar lib/  
        rm -rf uno
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add --all 
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    
