name: Remote Responder

on: [repository_dispatch]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: PONG
        if: github.event.action == 'ping'
        run: |
          curl -X POST https://api.github.com/repos/bxnce/uno/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: pull_repo
        if: github.event.action == 'ping'
        run: git clone https://github.com/Bxnce/uno.git
      - name: goto_uno
        if: github.event.action == 'ping'      
        run: |
          ls
          cd uno
          sbt package
      - name: move_back_cp_and_delete
        if: github.event.action == 'ping'
        run: | 
          ls
          rm -f uno_web/lib/uno*.jar ||true
      - name: testse
        if: github.event.action == 'ping'
        run: |
          ls
          mkdir -p lib 
          cp uno/target/scala-*/*.jar lib/  
          rm -rf uno
      - name: Commit files
        if: github.event.action == 'ping'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all 
          git commit -m "Add changes" -a
      - name: Push changes
        if: github.event.action == 'ping'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
